apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  namespace: devops-tools
  labels:
    type: local
spec:
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.0.1  # Replace with your NFS server address
    path: "/srv/volume/jenkins"      # Replace with your NFS export path
